# Title, decription, tagline and URL for your site
# Can be used in your theme by calling 'site.title' and so on
title: PS212
description: We are a strategic brand consultancy with big agency experience, operating at start-up speed.
url: http://www.ps212.com

# CloudCannon uses these:
source: src
destination: dist
exclude:

_comments:
  project_thumbnail_image: Image should be at least 450px square
  section_image: Image should be at least 1800px wide
  photo_path: Image should be at least 450px square
  sort_number: Lowest to highest (projects with no sort number come last)

project_types:
  - Design
  - Naming
  - Naming and Design
  - Strategy and Design

collections:
  projects:
    output: true
    permalink: /work/:slug/
  people:
    output: true
    permalink: /about/:slug/
  clients:
    output: false
defaults:
  -
    scope:
      path: ""
      type: projects
    values:
      class: project
      layout: project
  -
    scope:
      path: ""
      type: people
    values:
      class: about
      layout: about
  -
    scope:
      path: "cms.md"
    values:
      layout: "cms"
      permalink: "/cms/"
      _hide_content: true
  -
    scope:
      path: "index.html"
    values:
      class: home
      layout: default
      # permalink: "/"
  -
    scope:
      path: "about.html"
    values:
      class: about
      layout: default
      permalink: "/about/"
  -
    scope:
      path: "work.html"
    values:
      class: work
      layout: default
      permalink: "/work/"
  -
    scope:
      path: "clients.html"
    values:
      class: clients
      layout: default
      permalink: "/clients/"
  -
    scope:
      path: "contact.html"
    values:
      class: contact
      layout: default
      permalink: "/contact/"
